# config/advanced_training.yaml
# Advanced training configuration for Janus

# Environment Settings
env_type: "physics_discovery"
target_phenomena: "harmonic_oscillator"  # Options: harmonic_oscillator, pendulum, kepler
max_depth: 10
max_complexity: 30

# Training Mode
# Options: basic, selfplay, distributed, advanced
training_mode: "advanced"
total_timesteps: 1000000
n_agents: 4
use_curriculum: true

# Self-Play Configuration
league_size: 50
opponent_sampling: "prioritized_quality_diversity"
snapshot_interval: 10000

# Distributed Training
num_workers: 8
num_gpus: 4
use_pbt: true  # Population-based training
pbt_population_size: 4

# Monitoring
track_emergence: true
wandb_project: "janus-physics-discovery"
wandb_entity: "your-team"
checkpoint_freq: 10000
log_interval: 100

# Reward Configuration
reward_config:
  completion_bonus: 0.1
  mse_weight: -1.0
  complexity_penalty: -0.01
  depth_penalty: -0.001
  novelty_bonus: 0.2
  conservation_bonus: 0.5

# Curriculum Settings
curriculum_stages:
  - name: "simple"
    max_depth: 3
    max_complexity: 5
    success_threshold: 0.8
  - name: "intermediate"
    max_depth: 5
    max_complexity: 10
    success_threshold: 0.7
  - name: "complex"
    max_depth: 7
    max_complexity: 15
    success_threshold: 0.6
  - name: "advanced"
    max_depth: 10
    max_complexity: 25
    success_threshold: 0.5
  - name: "expert"
    max_depth: 12
    max_complexity: 40
    success_threshold: 0.4

# Data Settings
data_dir: "./data"
synthetic_data_params:
  n_samples: 2000
  noise_level: 0.05
  time_range: [0, 20]

# Output Paths
checkpoint_dir: "./checkpoints"
results_dir: "./results"
emergence_analysis_dir: "./results/emergence"

# Hyperparameter Search Space (for distributed mode)
hyperparam_search:
  lr: [1e-5, 1e-3]
  entropy_coeff: [0.0, 0.1]
  clip_param: [0.1, 0.3]
  train_batch_size: [2048, 4096, 8192]
  hidden_dim: [128, 256, 512]
  encoder_type: ["transformer", "treelstm"]

# Advanced Features
enable_conservation_detection: true
enable_symmetry_analysis: true
enable_dimensional_analysis: true
mine_abstractions_every: 5000
abstraction_min_frequency: 3

# Hardware Configuration
ray_config:
  num_cpus: 16
  num_gpus: 4
  object_store_memory: 10000000000  # 10GB
  placement_group_strategy: "SPREAD"

# Experiment Validation
run_validation_suite: true
validation_phases:
  - "known_law_rediscovery"
  - "robustness_testing"
  - "ablation_studies"
  - "transfer_learning"